# Generated by Django 4.2.29 on 2026-07-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="预警标题")),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("rainstorm", "暴雨"),
                            ("fire", "火灾"),
                            ("power_outage", "停电"),
                            ("earthquake", "地震"),
                            ("heat", "高温"),
                            ("cold_wave", "寒潮"),
                            ("flood", "内涝"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="预警类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("blue", "蓝色预警"),
                            ("yellow", "黄色预警"),
                            ("orange", "橙色预警"),
                            ("red", "红色预警"),
                        ],
                        max_length=20,
                        verbose_name="预警等级",
                    ),
                ),
                ("content", models.TextField(verbose_name="预警内容")),
                (
                    "community",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="影响社区"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否生效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_warnings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "灾害预警",
                "verbose_name_plural": "灾害预警",
                "ordering": ["-created_at"],
            },
        ),
    ]
