# Generated by Django 4.2.29 on 2026-07-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("warning", "预警通知"),
                            ("help_request", "求助通知"),
                            ("task", "任务通知"),
                            ("system", "系统通知"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="消息类型",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "related_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="关联对象类型"
                    ),
                ),
                (
                    "related_id",
                    models.IntegerField(blank=True, null=True, verbose_name="关联对象ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收人",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内消息",
                "verbose_name_plural": "站内消息",
                "ordering": ["-created_at"],
            },
        ),
    ]
