# Generated by Django 4.2.29 on 2026-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("warning", "灾害预警"),
                    ("help_request", "居民求助"),
                    ("task", "志愿者任务"),
                    ("system", "系统消息"),
                ],
                default="system",
                max_length=30,
                verbose_name="消息类型",
            ),
        ),
    ]
