# Generated by Django 5.2.8 on 2026-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('warning', '灾害预警'), ('help_request', '居民求助'), ('task', '志愿者任务'), ('service', '社区服务'), ('system', '系统消息')], default='system', max_length=30, verbose_name='消息类型'),
        ),
    ]
