# Generated by Django 4.2.29 on 2026-07-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("medical", "医疗求助"),
                            ("material", "物资求助"),
                            ("transfer", "转移求助"),
                            ("trapped", "被困求助"),
                            ("elderly", "老人求助"),
                            ("child", "儿童求助"),
                            ("fire", "火灾求助"),
                            ("flood", "积水求助"),
                            ("other", "其他求助"),
                        ],
                        max_length=30,
                        verbose_name="求助类型",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="紧急程度",
                    ),
                ),
                ("description", models.TextField(verbose_name="求助描述")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="求助地址"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("assigned", "已分配"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="求助居民",
                    ),
                ),
            ],
            options={
                "verbose_name": "居民求助",
                "verbose_name_plural": "居民求助",
                "ordering": ["-created_at"],
            },
        ),
    ]
