# Generated by ChatGPT for intelligent help-request summary support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='智能摘要'),
        ),
    ]
