# Generated by Django 5.2.8 on 2026-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_helprequest_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='completion_photo',
            field=models.FileField(blank=True, null=True, upload_to='completions/', verbose_name='完成确认照片'),
        ),
    ]
