# Generated by Django 5.2.8 on 2026-07-06 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服务名称')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='服务标识')),
                ('category', models.CharField(blank=True, default='', max_length=30, verbose_name='服务分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='服务说明')),
                ('required_skill', models.CharField(blank=True, default='', help_text='志愿者 skills 中需包含该关键字才能被自动排班', max_length=50, verbose_name='所需技能')),
                ('default_frequency', models.CharField(choices=[('weekly', '每周'), ('biweekly', '每两周'), ('monthly', '每月')], default='weekly', max_length=20, verbose_name='默认服务周期')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='预计时长(分钟)')),
                ('needs_health_record', models.BooleanField(default=False, verbose_name='是否录入健康记录')),
                ('icon', models.CharField(blank=True, default='🛎️', max_length=8, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', '每周'), ('biweekly', '每两周'), ('monthly', '每月')], default='weekly', max_length=20, verbose_name='服务周期')),
                ('preferred_weekday', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], default=0, verbose_name='首选星期')),
                ('preferred_time', models.CharField(blank=True, default='', max_length=10, verbose_name='首选时段')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='服务地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='最近排班日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='受益居民')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.servicetype', verbose_name='服务类型')),
            ],
            options={
                'verbose_name': '服务计划',
                'verbose_name_plural': '服务计划',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='计划上门日期')),
                ('status', models.CharField(choices=[('assigned', '已排班'), ('processing', '服务中'), ('completed', '已完成'), ('cancelled', '已取消'), ('missed', '已错过')], default='assigned', max_length=20, verbose_name='工单状态')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='服务地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='服务反馈')),
                ('completion_photo', models.FileField(blank=True, null=True, upload_to='service_visits/', verbose_name='完成凭证照片')),
                ('systolic', models.IntegerField(blank=True, null=True, verbose_name='收缩压(高压)')),
                ('diastolic', models.IntegerField(blank=True, null=True, verbose_name='舒张压(低压)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('health_note', models.TextField(blank=True, default='', verbose_name='健康备注')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_visits', to=settings.AUTH_USER_MODEL, verbose_name='受益居民')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='services.servicetype', verbose_name='服务类型')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='services.servicesubscription', verbose_name='关联服务计划')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_duties', to=settings.AUTH_USER_MODEL, verbose_name='服务志愿者')),
            ],
            options={
                'verbose_name': '上门服务工单',
                'verbose_name_plural': '上门服务工单',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
