# Generated by Django 5.2.8 on 2026-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='rotation_index',
            field=models.IntegerField(default=0, verbose_name='当前轮换位置'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='rotation_volunteers',
            field=models.JSONField(blank=True, default=list, verbose_name='轮换循环组(志愿者ID有序表)'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='服务时长(分钟)'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='需求说明'),
        ),
    ]
