# Generated by Django 5.2.8 on 2026-07-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesubscription_rotation_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='service_mode',
            field=models.CharField(choices=[('single', '单次'), ('recurring', '周期'), ('both', '通用')], default='both', help_text='single=只用于单次任务；recurring=只用于周期计划；both=两者皆可', max_length=20, verbose_name='适用方式'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='frequency',
            field=models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('biweekly', '每两周'), ('monthly', '每月')], default='weekly', max_length=20, verbose_name='服务周期'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='default_frequency',
            field=models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('biweekly', '每两周'), ('monthly', '每月')], default='weekly', max_length=20, verbose_name='默认服务周期'),
        ),
    ]
