# Generated by Django 5.2.8 on 2026-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicetype_service_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='confirm_photo',
            field=models.FileField(blank=True, null=True, upload_to='service_visits/', verbose_name='居民确认照片'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='居民确认完成时间'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='志愿者提交完成时间'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='status',
            field=models.CharField(choices=[('assigned', '已排班'), ('processing', '服务中'), ('pending_confirm', '待居民确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('missed', '已错过')], default='assigned', max_length=20, verbose_name='工单状态'),
        ),
    ]
