# Generated by Django 5.2.8 on 2026-07-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicevisit_confirm_photo_servicevisit_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubscription',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='preferred_slot',
            field=models.IntegerField(blank=True, choices=[(8, '08:00-09:00'), (9, '09:00-10:00'), (10, '10:00-11:00'), (11, '11:00-12:00'), (12, '12:00-13:00'), (13, '13:00-14:00'), (14, '14:00-15:00'), (15, '15:00-16:00'), (16, '16:00-17:00'), (17, '17:00-18:00'), (18, '18:00-19:00'), (19, '19:00-20:00')], null=True, verbose_name='首选时段(整点槽)'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_distance_m',
            field=models.IntegerField(blank=True, help_text='报到位置与服务地址的直线距离；超 500 米标记远程报到', null=True, verbose_name='报到距离(米)'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='报到纬度'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='报到经度'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_photo',
            field=models.FileField(blank=True, null=True, upload_to='service_visits/', verbose_name='报到照片'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_remote',
            field=models.BooleanField(default=False, verbose_name='远程报到(距离异常)'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='scheduled_slot',
            field=models.IntegerField(blank=True, choices=[(8, '08:00-09:00'), (9, '09:00-10:00'), (10, '10:00-11:00'), (11, '11:00-12:00'), (12, '12:00-13:00'), (13, '13:00-14:00'), (14, '14:00-15:00'), (15, '15:00-16:00'), (16, '16:00-17:00'), (17, '17:00-18:00'), (18, '18:00-19:00'), (19, '19:00-20:00')], help_text='DDL=该时段结束；志愿者须在此前到场报到，否则转已错过并扣分', null=True, verbose_name='预约时段(整点槽)'),
        ),
    ]
