# Generated by Django 5.2.8 on 2026-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicesubscription_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到场报到时间'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='status',
            field=models.CharField(choices=[('assigned', '已排班'), ('checked_in', '已报到'), ('processing', '服务中'), ('pending_confirm', '待居民确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('missed', '已错过')], default='assigned', max_length=20, verbose_name='工单状态'),
        ),
    ]
