# Generated by Django 4.2.29 on 2026-07-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "已分配"),
                            ("accepted", "已接单"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="处理反馈"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="接单时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "help_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_task",
                        to="requests_app.helprequest",
                        verbose_name="关联求助",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunteer_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="志愿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "志愿者任务",
                "verbose_name_plural": "志愿者任务",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
