# Generated by Django 4.2.29 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "已分配"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="assigned",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
    ]
