# Generated by Django 5.2.8 on 2026-07-06 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_helprequest_completion_photo'),
        ('tasks', '0002_alter_volunteertask_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('family', '家庭原因'), ('illness', '生病'), ('distance', '距离过远'), ('work', '工作冲突'), ('emergency', '突发状况'), ('other', '其他')], default='other', max_length=20, verbose_name='取消原因')),
                ('note', models.TextField(blank=True, default='', verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取消时间')),
                ('help_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests_app.helprequest', verbose_name='关联求助')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='tasks.volunteertask', verbose_name='任务')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='志愿者')),
            ],
            options={
                'verbose_name': '任务取消记录',
                'verbose_name_plural': '任务取消记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
