# Generated by Django 5.2.8 on 2026-07-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tasks', '0003_taskcancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcancellation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='services.servicevisit', verbose_name='上门服务工单'),
        ),
    ]
