# Generated by Django 4.2.29 on 2026-07-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="物资名称")),
                ("category", models.CharField(max_length=50, verbose_name="物资类别")),
                ("quantity", models.IntegerField(default=0, verbose_name="库存数量")),
                (
                    "unit",
                    models.CharField(default="件", max_length=20, verbose_name="单位"),
                ),
                (
                    "storage_location",
                    models.CharField(max_length=255, verbose_name="存放位置"),
                ),
                (
                    "warning_quantity",
                    models.IntegerField(default=10, verbose_name="库存预警值"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "应急物资",
                "verbose_name_plural": "应急物资",
            },
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="避难点名称")),
                ("address", models.CharField(max_length=255, verbose_name="避难点地址")),
                ("capacity", models.IntegerField(default=0, verbose_name="可容纳人数")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "避难点",
                "verbose_name_plural": "避难点",
            },
        ),
    ]
