# Generated by ChatGPT for material lifecycle management

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='material',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='过期日期'),
        ),
        migrations.AddField(
            model_name='material',
            name='expiry_warning_days',
            field=models.IntegerField(default=30, verbose_name='临期预警天数'),
        ),
    ]
