# Generated by ChatGPT for intelligent dispatch scoring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='擅长任务'),
        ),
    ]
