# Generated by Django 5.2.8 on 2026-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='志愿积分'),
        ),
    ]
