# Generated by Django 5.2.8 on 2026-07-07 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='志愿者资料经管理员审核/面试通过后置为已认证', verbose_name='是否已认证'),
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('community', models.CharField(blank=True, default='', max_length=100, verbose_name='所属社区')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='详细地址')),
                ('skills', models.CharField(blank=True, default='', max_length=255, verbose_name='擅长技能')),
                ('note', models.TextField(blank=True, default='', verbose_name='自我介绍')),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='volunteer_apps/', verbose_name='身份证正面')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='volunteer_apps/', verbose_name='身份证反面')),
                ('skill_cert', models.FileField(blank=True, null=True, upload_to='volunteer_apps/', verbose_name='技能/资格证书')),
                ('health_cert', models.FileField(blank=True, null=True, upload_to='volunteer_apps/', verbose_name='健康证')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='volunteer_apps/', verbose_name='个人形象照')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('interviewing', '面试中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_application', to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'verbose_name': '志愿者申请',
                'verbose_name_plural': '志愿者申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
